version: "3.8"

services:
  app:
    image: jeongminju45/myapp:${IMAGE_TAG}
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    command: [ "/bin/sh", "-c", "until nc -z redis 6379; do echo waiting for redis; sleep 1; done; java -jar /app.jar" ]
    networks:
      - app-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - app-net

volumes:
  redis-data:

networks:
  app-net: