version: "3.8"

services:
  app:
    image: jeongminju45/myapp:latest
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    command: ["/bin/sh", "-c", "while ! (echo > /dev/tcp/redis/6379) 2>/dev/null; do echo waiting for redis; sleep 1; done; java -jar /app.jar"]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
