name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: jeongminju45/myapp

    steps:
      # 1. 깃허브 저장소 코드 내려받기
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # ci에서 저장한 artifacts(.jar) 파일 cd에서 다운 받기
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.SCOPE_TOKEN }}

      # 구조 파악
      - name: List contents
        run: ls -R

      # .jar 파일 올바른 폴더경로로 옮기기
      - name: Move downloaded JAR to expected path
        run: |
          mkdir -p build/libs
          mv myapp-0.0.1-SNAPSHOT.jar build/libs/


      # 3. JDK 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 4. 버전 정보 정의 (날짜 기반 태그)
      - name: Set VERSION
        id: set_version
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      # 5. Docker 이미지 빌드 및 푸시 (고유 태그 + latest)
      - name: Build & Push Docker Image
        run: |
          docker build --build-arg JAR_FILE=myapp-0.0.1-SNAPSHOT.jar \
            -t $IMAGE_NAME:${{ steps.set_version.outputs.VERSION }} \
            -t $IMAGE_NAME:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $IMAGE_NAME:${{ steps.set_version.outputs.VERSION }}
          docker push $IMAGE_NAME:latest
        shell: bash

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.yml
          target: /home/ec2-user/myapp/


      # 6. EC2로 배포 (고유 태그로 pull + 덮어쓰기)
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_TAG=${{ steps.set_version.outputs.VERSION }}
            IMAGE_NAME=jeongminju45/myapp
            cd /home/ec2-user/myapp
            echo "🧪 IMAGE_NAME=$IMAGE_NAME"

            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            docker-compose down
            docker rmi $IMAGE_NAME:$IMAGE_TAG || true
            docker pull $IMAGE_NAME:$IMAGE_TAG

            sed -i "s|image:.*|image: $IMAGE_NAME:$IMAGE_TAG|" docker-compose.yml
            docker-compose up -d
