name: Continuous Integration

on:
  push:
    branches: [develop]
    paths:
      - "**.java"
      - "build.gradle*"
      - "asyncapi.yaml"

jobs:
  build-and-generate-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치 (AsyncAPI CLI 실행용)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. AsyncAPI Generator 전역 설치
      - name: Install AsyncAPI Generator
        run: npm install -g @asyncapi/generator

      # 4. AsyncAPI → HTML 문서 자동 생성
      - name: Generate HTML Docs
        run: |
          npx @asyncapi/generator asyncapi.yaml @asyncapi/html-template -o src/main/resources/static/docs

      # 5. 문서 변경사항 커밋 & 푸시
      - name: Commit and Push Generated Docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add src/main/resources/static/docs
          git commit -m "Auto-update AsyncAPI docs"
          git push

      # 6. JDK 17 설치 (Spring Boot 빌드용)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 7. gradlew 실행 권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 8. JAR 빌드 (테스트 제외)
      - name: Build JAR
        run: ./gradlew build -x test

      # 9. 빌드된 JAR 업로드 → CD에서 사용
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/myapp-0.0.1-SNAPSHOT.jar
