name: Generate AsyncAPI Docs

on:
  push:
    paths:
      - "asyncapi.yaml"

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AsyncAPI Generator
        run: npm install -g @asyncapi/generator

      - name: Generate HTML Docs
        run: |
          npx @asyncapi/generator asyncapi.yaml @asyncapi/html-template -o src/main/resources/static/docs

      - name: Commit and Push Generated Docs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add src/main/resources/static/docs
          git commit -m "Auto-update AsyncAPI docs"
          git push
